### PR TITLE
added methods to PlyElement

### PR DESCRIPTION
**Pull request by athompson673**
Added "contains" and "len" methods to PlyElement to easily test property membership and get length of element.

### CODE REVIEW

**Comment by dranjan** [comment]
Thanks for the pull request! I think the new feature is fine, and the code looks fine as well. I don't think the CI is working any more (#39), but I can still run the unit tests locally, not that there's much risk with a change like this anyway.

A couple things:
- We might as well add unit tests for the new functionality.
- The changelog should be updated.

I can take care of those by the end of the week probably, but feel free to take the initiative yourself. (I also realize at this point that I should probably add a contributors' guide document as many other projects do.)

After merging I can bump the version and update PyPI.

**Comment by athompson673** [comment]
I have to admit, I don't know a whole lot about pytest or unit tests in general, so I wouldn't know best practice for that... I'll leave versioning up to you.

testing contains may simply look like:
```
def test_contains()
```

**Comment by athompson673** [comment]
oops, wrong button...

**Comment by dranjan** [comment]
> I have to admit, I don't know a whole lot about pytest or unit tests in general, so I wouldn't know best practice for that...

No worries. Sorry, I realize I'm a little behind schedule here, but I haven't forgotten about this.

> I'll leave versioning up to you.

Yep, that's the maintainer's job (me). :-)

**Comment by dranjan** [comment]
Apologies, it has been over a month. This was just merged, and the release should be out soon.

**Pull request merged**
