### PR TITLE
Use np.memmap for simple elements in binary files

### PR DESCRIPTION
**Pull request by Zac-HD**
For simple elements in binary files, .ply format uses the same bytes
on-disk as in-memory.  With `numpy.memmap`, we can take advantage of
this - reads are backed by (buffered) disk, and writes store the changes
in memory (the file-on-disk is read-only).

Motivation:  most photogrammetery packages can export to .ply format,
and at landscape scale - yay drones - the files for a single scene can
be several GB each and collectively too large for memory.  On my test
dataset, avoiding the read-write-to-memmap pattern avoids ~40GB of disk
IO per run :)

### CODE REVIEW

**Comment by dranjan** [comment]
Thanks for contributing!  The feature looks good.  The only major issue I see at the moment is unit test coverage.  Ideally we should test both mappable and non-mappable files (if such exist), and for the mappable cases, with other PLY elements before and after the memory-mapped element (to make sure the seek/tell logic is working correctly).  Also, this statement is important and should probably be verified in a test:

> ...reads are backed by (buffered) disk, and writes store the changes
in memory (the file-on-disk is read-only).

Unfortunately, it seems I've neglected to include any test coverage metrics in the unit testing setup, but if you can cope, feel free to write the tests yourself.  Otherwise, I can get around to it in the near future.  (I've used the [pytest-cov](https://pypi.python.org/pypi/pytest-cov/) package in an ad-hoc manner, but like I said, it isn't part of the test configuration yet.)

**Comment by Zac-HD** [comment]
Files can be non-mappable (if ASCII, or not existing on disk); otherwise the memmaps are used on a per-element basis for all non-list elements.  I agree that testing unusual orders of elements for seek/tell is a good idea.  The buffering behavior is [provided directly by Numpy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html) (`mode=c`), so I'm not sure we need to test it specifically.

I'll leave tests to you if that's OK, as I'm unfamiliar with most of the setup you're using and can't dedicate much time to this.  

When I do (eventually) have time though, I've been meaning to explore [Hypothesis](https://hypothesis.readthedocs.io).  Would it be useful to try and confirm that for example that read/write/read cycles are byte-perfect?

**Comment by dranjan** [comment]
Just checking in: I'm still alive, and I did not forget about this.  I didn't have much time for this over the past few weeks, but I hope to review and merge this within a few days.  I did manage to integrate pytest-cov into the automated testing, which makes it easier to see whether the feature is being used.

@Zac-HD - do you know how to construct a binary file that can't be memory mapped?  Note that currently only true file objects are supported, not file-like objects like `StringIO` (limitation of `numpy.fromfile`).

**Comment by Zac-HD** [comment]
No worries, I've also been busy with other projects.

I think using `tempfile.TemporaryFile` might work on *nix systems where the parent directory is unlinked (meaning there's no valid path to the file) - though in my code here it won't try if the file doesn't exist.  Similarly, this code won't even try to memmap a list element as that's handled elsewhere.

Trying to memmap a file which is too short doesn't throw an exception, just zeros the extra elements (on posix, at least.  It's kinda undefined).  So I don't know how to contruct a file full of bytes that `np.memmap` can't read as an array.

**Comment by dranjan** [comment]
Okay, for real this time. :-) Thanks again for the pull request.  I ended up removing the code branch that called `fromfile`, since I think it supports the  same files as `memmap` (i.e., something exposing a file descriptor).

If I understand correctly, it might still be advantageous to use `fromfile` sometimes, such as when the files in question are very small, but for now I'm opting to keep things simple and only cross that bridge if we get there, at which point maybe we can allow advanced users to choose between loading methods.

**Pull request merged**
